### ISSUE TITLE
Sudo package installation

### ISSUE THREAD

**Issue by jmauro** [chef-cookbooks/sudo#128]
### Cookbook version
5.3.1
### Chef-client version
chef-12.18.31-1.
### Platform Details
CetnOS 6/7
### Scenario:
If a refreshly installed server doesn't have the sudo package installed (this happened when using only @core packages), the cookbook does not install the package.

### Steps to Reproduce:
Install a fresh CentOS server wth on @core group packages

### Expected Result:
The sudo package to be installed

As far as I can see there was a changed that setup sudo only on docker I was wondering what are you only handling this cases?

**Comment by tas50** [comment]
We initially added sudo installation, but it turned out to be super problematic for a lot of users. After wrapping it a few different ways it was still causing users a lot of pain. I think we're just going to have to assume sudo is there for the resource. I'm open a gate that solves it for everyone if you have something, but right now it's just a pile of hurt trying to implement something everyone can agree on.

**Comment by kamaradclimber** [comment]
I'm not clear on the utility of sudo cookbook if it does not install sudo package.
Could you detail the pain encountered by users related to sudo package installation?
